version: "3.8"

services:
  # Database
  troy-db:
    container_name: 'troy-db'
    image: 'postgres:15'
    ports:
      - "15432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/dbdata/
    environment:
      - POSTGRES_DB=troy
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
  troy-db-test:
    container_name: 'troy-db-test'
    image: 'postgres:15'
    ports:
      - '6432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/dbdata/
    environment:
      - POSTGRES_DB=troy_test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
