CREATE TABLE IF NOT EXISTS troy.budget (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    value DECIMAL NOT NULL,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT unique_month_year UNIQUE(month, year)
);